#!/usr/bin/env zsh

# pyenv
export PYENV_ROOT="$HOME/.pyenv"

# Add pyenv root to PATH
if [[ -d $PYENV_ROOT ]];then
    PATH="$PYENV_ROOT/bin:$PATH"
fi

# Initialize pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
