# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git ssh-agent virtualenv zsh-syntax-highlighting)

# User configuration

source $ZSH/oh-my-zsh.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

alias ws="cd ~/Workspace"
alias dl="cd ~/Downloads"
alias l="ls -lha"
alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
alias ngstart='sudo launchctl start homebrew.mxcl.nginx'
alias ngstop='sudo launchctl stop homebrew.mxcl.nginx'
alias gs="git status"
alias gd="git difftool"
alias gitcheck="git ls-files --error-unmatch"
alias jkserve="bundle exec jekyll serve"
alias e="/Applications/Emacs.app/Contents/MacOS/Emacs"
alias ec="emacsclient -t"
alias er="launchctl unload /Library/LaunchAgents/gnu.emacs.daemon.plist && launchctl load /Library/LaunchAgents/gnu.emacs.daemon.plist"
alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
alias vi="vim"

[ -e ~/.zshrc.local ] && source ~/.zshrc.local
